kind: pipeline
type: docker
name: default
volumes:
  - name: ssh_keys
    host:
      path: /root/.ssh
clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    volumes:
      - name: ssh_keys
        path: /root/.ssh
    commands:
      - git init
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1
      - git checkout origin/$DRONE_COMMIT_BRANCH -ft

  - name: build
    image: golang:1.19.0-alpine3.16
    depends_on: [clone]
    commands:
      - pwd
      - ls -a
      - go env -w GOPROXY=https://goproxy.cn,direct
      - GOOS=linux GOARCH=amd64 go build -o main

  - name: build dummy docker file and publish
    depends_on: [ build ]
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: registry.cn-shanghai.aliyuncs.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-aliyun-oss
      tags: latest
